version: "3.9"

services:
  djangoapp:
    container_name: djangoapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=manas2001
      - POSTGRES_DB=core_db
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    environment:
      - POSTGRES_DB= core_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=manas2001
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}